# Server endpoint
server_endpoint = "/run/user/1000/clipcat/grpc.sock"
# The preview len
preview_length = 100

[log]
# No file_path because i don't care of the log
emit_journald = false
emit_stdout = false
emit_stderr = false
level = "INFO"
