#!/bin/bash

# Config created by Skignes https://github.com/skignes/Dotfiles
# Copyright (C) 2025 Skignes
# Distributed under the GPLv3+ License https://www.gnu.org/licenses/gpl-3.0.html

show_menu() {
    # Check if Wi-Fi is enabled
    wifi_status=$(nmcli radio wifi)

    if [ "$wifi_status" = "enabled" ]; then
        # Show the deactivate wifi
        echo "Deactivate Wi-Fi"
        # Add the Network SSID
        nmcli -t -f SSID,SECURITY device wifi list | awk -F: '{print $1}' | grep -v '^$' | sort -u
    else
        # Show the activate wifi
        echo "Activate Wi-Fi"
    fi
}

while true; do
    # Select your network
    selected=$(show_menu | rofi -theme ~/.config/rofi/Network.rasi -dmenu -p "Select a SSID:")

    if [ -n "$selected" ]; then
        # Check if the selected option is to deactivate or activate Wi-Fi
        if [ "$selected" = "Deactivate Wi-Fi" ]; then
            nmcli radio wifi off
            break
        elif [ "$selected" = "Activate Wi-Fi" ]; then
            nmcli radio wifi on
            break
        fi

        # Check the security of the network
        security=$(nmcli -t -f SECURITY device wifi list | grep "$selected" | cut -d':' -f2)

        # Check if the connection is there
        connection_exists=$(nmcli connection show --active | grep "$selected")

        if [[ "$security" != "none" ]]; then
            # Check if the password is there
            password_saved=$(nmcli connection show "$selected" | grep "802-11-wireless-security.psk")

            if [ -n "$password_saved" ]; then
                # Connect
                nmcli device wifi connect "$selected"
                break
            else
                # WARNING: Might not be secure
                # Prompt for password
                password=$(rofi -theme ~/.config/rofi/Network.rasi -dmenu -password -p "Enter password for $selected:")
                if [ -n "$password" ]; then
                    nmcli device wifi connect "$selected" password "$password"
                    break
                fi
            fi
        else
            # Connect
            nmcli device wifi connect "$selected"
            break
        fi
    else
        break
    fi
done

